name: doctl
version: git
summary: The official DigitalOcean command line interface
description: |
  doctl allows you to interact with the DigitalOcean API via the command line.
  It supports most functionality found in the control panel. You can create,
  configure, and destroy DigitalOcean resources like Droplets, Kubernetes
  clusters, firewalls, load balancers, database clusters, domains, and more.
license: Apache-2.0

base: core20
grade: stable
confinement: strict

parts:
  doctl:
    source: https://github.com/digitalocean/doctl
    plugin: go
    source-type: git

apps:
  doctl:
    command: bin/doctl-launch
    plugs:
      - home
      - network
      - ssh-keys
      - dot-docker
      - doctl-config
      - kube-config
