name: doctl
adopt-info: doctl
summary: The official DigitalOcean command line interface
description: |
  doctl allows you to interact with the DigitalOcean API via the command line.
  It supports most functionality found in the control panel. You can create,
  configure, and destroy DigitalOcean resources like Droplets, Kubernetes
  clusters, firewalls, load balancers, database clusters, domains, and more.
license: Apache-2.0

base: core20
grade: stable
confinement: strict

parts:
  doctl:
    source: https://github.com/digitalocean/doctl
    override-pull: |
      snapcraftctl pull
      version=$(git describe --abbrev=0)
      snapcraftctl set-version ${version}
    plugin: go
    source-type: git

apps:
  doctl:
    command: bin/doctl
    plugs:
      - home
      - network
      - ssh-keys
